package com.example.tabsplitter.ui.theme

import androidx.compose.ui.graphics.Color

// Light Colors
val LightPrimary = Color(0xFF006A60)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF74F8E5)
val LightOnPrimaryContainer = Color(0xFF00201C)
val LightSecondary = Color(0xFF4A635F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E2)
val LightOnSecondaryContainer = Color(0xFF05201C)
val LightTertiary = Color(0xFF456179)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCCE5FF)
val LightOnTertiaryContainer = Color(0xFF001E31)
val LightBackground = Color(0xFFFAFDFB)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFFAFDFB)
val LightOnSurface = Color(0xFF191C1B)
val LightSurfaceVariant = Color(0xFFDAE5E1)
val LightOnSurfaceVariant = Color(0xFF3F4946)
val LightOutline = Color(0xFF6F7976)

// Dark Colors
val DarkPrimary = Color(0xFF53DBC9)
val DarkOnPrimary = Color(0xFF003731)
val DarkPrimaryContainer = Color(0xFF005047)
val DarkOnPrimaryContainer = Color(0xFF74F8E5)
val DarkSecondary = Color(0xFFB1CCC6)
val DarkOnSecondary = Color(0xFF1C3531)
val DarkSecondaryContainer = Color(0xFF334B47)
val DarkOnSecondaryContainer = Color(0xFFCCE8E2)
val DarkTertiary = Color(0xFFADCAE6)
val DarkOnTertiary = Color(0xFF133248)
val DarkTertiaryContainer = Color(0xFF2C4960)
val DarkOnTertiaryContainer = Color(0xFFCCE5FF)
val DarkBackground = Color(0xFF191C1B)
val DarkOnBackground = Color(0xFFE0E3E1)
val DarkSurface = Color(0xFF191C1B)
val DarkOnSurface = Color(0xFFE0E3E1)
val DarkSurfaceVariant = Color(0xFF3F4946)
val DarkOnSurfaceVariant = Color(0xFFBEC9C5)
val DarkOutline = Color(0xFF899390)
